### ISSUE TITLE
notification position

### ISSUE THREAD

**Issue by demeldoo** [cscart/cscart-boilerplate#10]
hello,

here is a small issue 

https://drive.google.com/file/d/0B4wkwfPFu50ZWjRLaWZ1NFlRcEU/view?usp=drivesdk

**Comment by amelekesov** [comment]
I wouldn't consider it a bug that the notification shows up in the top right corner of the screen, and not within the container. That way, if a user has a large display, the notification won't hide the content.

**Comment by kugimiya** [comment]
Hello, @demeldoo.
Boilerplate create special for creating your own customization of themes. Just customize. :)
