### ISSUE TITLE
images displayed in real size

### ISSUE THREAD

**Issue by demeldoo** [cscart/cscart-boilerplate#19]
on product page image is displayed in original size

https://drive.google.com/file/d/0B4wkwfPFu50ZckQ4RVF2dE55SVk/view?usp=drivesdk

**Comment by demeldoo** [comment]
larger then original

**Comment by amelekesov** [comment]
Fixed by https://github.com/cscart/cscart-boilerplate/commit/6ec0f928047fca4d7bbdd93cd8a6d954d6066502
