### ISSUE TITLE
brand filter with outer navigation

### ISSUE THREAD

**Issue by demeldoo** [cscart/cscart-boilerplate#2]
https://drive.google.com/file/d/0B4wkwfPFu50ZdE0xU0xoMWhsS2M/view?usp=drivesdk

**Comment by amelekesov** [comment]
It isn't a bug. When developing a theme, you can use CSS to hide the navigation or to move it anywhere you want.

**Comment by demeldoo** [comment]
this theme is planned to be included in cs cart and i don't see the point closing this and not resolving.

probably you're right that we can move it to proper position. but there are 300000 of  us which should move this to proper position ;)

**Comment by amelekesov** [comment]
FIxed by https://github.com/cscart/cscart-boilerplate/commit/171605b
