### ISSUE TITLE
Single level categories do not work as menus

### ISSUE THREAD

**Issue by camerojo** [cscart/cscart-boilerplate#21]
Single level categories do not function as menu items. Clicking on the category does nothing.

I think that the problem is with the data-toggle="dropdown" attribute. If you remove that the link works as expected.

In the html below, you can see that there is no drop down because the Category Olives has no subcategories. The href link will only work if you remove the data-toggle attribute.

``` html
 <li class="dropdown  active">
   <a href="http://localhost/fromtheproducer/olives/" class="dropdown-toggle" 
   data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
      Olives  <span class="caret"></span>
   </a>
</li>
```

**Comment by amelekesov** [comment]
Fixed by https://github.com/cscart/cscart-boilerplate/commit/7ff5167b3e0b5666bb0cd7984c5463a7024ebf5e
