### ISSUE TITLE
Add to cart popup on mobile doesn't display correct

### ISSUE THREAD

**Issue by Alexder** [cscart/cscart-boilerplate#27]
When on mobile press "Add to cart" button, popup doesn't display correctly
![screenshot_2016-01-28-11-51-21_com yandex browser](https://cloud.githubusercontent.com/assets/965842/12634604/04e29386-c5b6-11e5-98af-df25d7198808.png)

**Comment by amelekesov** [comment]
Fixed by https://github.com/cscart/cscart-boilerplate/commit/ea4ea48f5cfc34e16fbe155d9143df6f2866398c
