### ISSUE TITLE
Ajax error when using filters

### ISSUE THREAD

**Issue by phungdiep** [cscart/cscart-boilerplate#28]
Hi, this interface ajax error when I try to use the filter.
![loi](https://cloud.githubusercontent.com/assets/16997774/12707954/bc27618e-c8cc-11e5-85b6-96f8a98c5726.png)

**Comment by amelekesov** [comment]
Could you describe in detail how to reproduce the issue? What's the version of CS-Cart and browser?

**Comment by kugimiya** [comment]
Bug was fixed long time ago.
