### ISSUE TITLE
Can't get rid of truncate product name

### ISSUE THREAD

**Issue by Alexder** [cscart/cscart-boilerplate#29]
I use products_multicolumns as default view in categories. Now products appears with truncated product name, I tried to change setting in "product_list_templates / products_multicolumns.tpl", changed "show_trunc_name=true" to "show_name=true". But it has no effect.
I checked file "common/product_data.tpl", and found that conditions for "show_name" and "show_trunc_name" are the same, always should appear full name of product. 
Why it appears as truncated is because of css
`.product-title {white-space: nowrap;}`

I'm not sure is it a bug or not, but I think conditions for show_trunc_name and show_name should be different.

**Comment by amelekesov** [comment]
It is not a bug. That was a bad idea on our part to truncate product names instead of using css text-overflow.
