### ISSUE TITLE
Product features list looks not pretty

### ISSUE THREAD

**Issue by Alexder** [cscart/cscart-boilerplate#30]
On product page features list looks not so good, I think at least need to make list-unstyled
<img width="501" alt="2016-02-01 13 02 05" src="https://cloud.githubusercontent.com/assets/965842/12709188/0e7d0350-c8e4-11e5-91ca-66eeb9e40f3b.png">

**Comment by amelekesov** [comment]
Fixed by https://github.com/cscart/cscart-boilerplate/commit/c937597863d6d0aa24e5b4c5dda0421a88ece4ad
