### ISSUE TITLE
Font Awesome + Glyphicons conflict

### ISSUE THREAD

**Issue by drahosistvan** [cscart/cscart-boilerplate#32]
Hi there,

You wrote this in the official blog post:

> The Boilerplate theme supports both Glyphicons, which ship with Bootstrap, and Font Awesome icons. These icons simplify and speed up theme development—you add a ready-made icon to your theme by copying the pre-cooked code.

If I install fontawesome icon pack, it conflicts with the built-in Glyphicons pack, because you use both of the classes. If I remove the glyphicons CSS rules, it works, however this is not the best functionality.

**My suggestions:**
- It should be a good solution, to write an icon wrapper with less, and the shop owner, or the developer can choose the icon pack, or even icons individually.
- Create a Smarty variable, and it can be switched from Glyphicons to Font Awesome

What do you think?

**Comment by amelekesov** [comment]
Why use a smarty variable instead of a class? I think it overcomplicates things.

**Comment by drahosistvan** [comment]
https://github.com/cscart/cscart-boilerplate/blob/master/templates/blocks/my_account.tpl
The usage of the icon is:
`<i class="glyphicon glyphicon-user fa fa-user"></i>`
If both glyphicons and font awesome is installed, the icon display not working, because the 2 icon packs conflicts.
This can be a possible solution:
`<i class="{if $icon_pack == 'fa'}fa fa-user{else}glyphicon glyphicon-user{/if}"></i>`

**Comment by amelekesov** [comment]
I think that using both glyphicons and font awesome is a bad idea.
These packs have different icon styles, and we expected that people would only use one pack or the other.

**Comment by drahosistvan** [comment]
Yes, they have different styles, but there are [a lot of situations](https://www.google.hu/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=use%20both%20font%20awesome%20and%20glyphicons), when users wants to use both of the packs. Or maybe sometimes you just use the glyphicon set, but want to include social media icons easliy.
The glyphicon and the font awesome pack have a lot of same icons, but there are a lot of differences, too.

My other idea is, to create a wrapper for the main icons, used by the theme, and the developer can use both of the libraries without any conflict.

Eg.

`<i class="icons icon-user"></i>`

And there will be an icons.less file, where you can setup your icon easily, and even you can import your own, custom designed font-icon pack, too. This idea gives the developer a much more readable code, and more options to configure the theme.

What do you think?

**Comment by amelekesov** [comment]
I don't think it's a good idea. ) It would create confusion with the icons and make the page heavier.
I think that you should switch to fontawesome if glyphicons aren't enough.
Using 2 packs simultaneously isn't the best decision both in terms of design and performance.

**Comment by dhaupin** [comment]
Not understanding this issue. We use both Glyph and FontAwesome without collisions. The key is to do it at CSS and overwrite the elements :before pseudo selector.  Example, if you want to change the cart icon to FA instead:

```
.ty-icon-basket:before {
	font-family: fontawesome;
	content: "\f07a"; /* fa-shopping-cart */
}
```
