### ISSUE TITLE
Unnecessary element in sorting

### ISSUE THREAD

**Issue by Alexder** [cscart/cscart-boilerplate#33]
In sorting panel there is unnecessary element "Action" which does nothing
<img width="455" alt="2016-02-04 17 05 59" src="https://cloud.githubusercontent.com/assets/965842/12810560/ed3e11a4-cb61-11e5-99ca-438d42e3a6a3.png">

Need to delete line #61 `<li><a href="#">Action</a></li>` in templates / views / products / components / sorting.tpl

**Comment by amelekesov** [comment]
Fixed by https://github.com/cscart/cscart-boilerplate/commit/88a5046628d8fba528654fc94da25f4979979ba1
