### ISSUE TITLE
my_changes

### ISSUE THREAD

**Issue by thanasisloi7** [cscart/cscart-boilerplate#35]
Hi, how can i use my_changes addon to this theme? I am trying but it doesn't work. 
Boilerplate support my_changes?

**Comment by amelekesov** [comment]
Could you describe in detail how to reproduce the issue?

**Comment by thanasisloi7** [comment]
i have already install and activate my_changes addon. I create for example "cscart-boilerplate-master / templates / addons / my_changes / products / view_main_info.override.tpl"
but the changes don't apply. Is anything else i need to do?

**Comment by Alexder** [comment]
I think you have the wrong path, if you use hooks it should be:
"cscart-boilerplate-master / templates / addons / my_changes / hooks / products / view_main_info.override.tpl"
also remember to clear the cache

**Comment by amelekesov** [comment]
Alexder is right, you have used the wrong path.
http://docs.cs-cart.com/4.3.x/developer_guide/addons/hooking/tpl_hooks.html
