### ISSUE TITLE
Product image doesn't display in shopping cart block

### ISSUE THREAD

**Issue by Alexder** [cscart/cscart-boilerplate#36]
Product image doesn't display in shopping cart block, but if check code it should appear
<img width="360" alt="2016-02-15 12 43 23" src="https://cloud.githubusercontent.com/assets/965842/13040045/005204d4-d3e2-11e5-98b1-fd292ed3fe8c.png">

I think the problem is in this css:
`.media-body {
    width: 10000px;
}`
if change it to:
`.media-body {
    width: auto;
}`
then it displays correct:
<img width="367" alt="2016-02-15 12 46 57" src="https://cloud.githubusercontent.com/assets/965842/13040064/3b81f302-d3e2-11e5-9cc4-68e8ae9e01ff.png">

**Comment by amelekesov** [comment]
Fixed by https://github.com/cscart/cscart-boilerplate/commit/1c3c3c55bcf70d3ddbf9d6ea5659b4b6b89df8ae
