### ISSUE TITLE
Add-on styling seems to be outdated (Call Request)

### ISSUE THREAD

**Issue by ghost** [cscart/cscart-boilerplate#40]
Boilerplate:

``` smarty
{** block-description:tmpl_call_request **}
<div class="cr-block">
    <div class="cr-phone">
        <span class="cr-phone-prefix">{$phone_number.prefix}</span>
        <span class="cr-phone-number"> {$phone_number.postfix}</span>
    </div>
    <div class="cr-link">
        {include file="addons/call_requests/views/call_requests/components/popup.tpl" product=false link_text=__("call_requests.request_call")}
    </div>
</div>
```

CS-Cart 4.3.5 Addon:

``` smarty
{** block-description:tmpl_call_request **}

<div class="ty-cr-phone-number-link">
    <div class="ty-cr-phone"><span class="ty-cr-phone-prefix">{$phone_number.prefix}</span><span>{$phone_number.postfix}</span></div>
    <div class="ty-cr-link">{include file="addons/call_requests/views/call_requests/components/popup.tpl" product=false link_text=__("call_requests.request_call")}</div>
</div>
```

-- Others might have a similar issue.

[first issue on git!]

**Comment by eermol** [comment]
Hi! Actually, we decided to abandon from CSS prefix "ty-" in boilerplate to the side of clean bootstrap HTML and CSS as more as we can. That's why styling might seems to be outdated. 

P.S. Congratz with your first issue :)

**Comment by ghost** [comment]
Hi, thanks for the response. 

That makes sense. You're trying to keep the code as minimal as possible. 

Quick pointer; 
What I assume I should do is customize the module with ty- _if I need to_ yes? 

Thanks again,
Nipun Senadheera

**Comment by eermol** [comment]
Actually you can customize it as you want :) .But I'm think default classes will be quite enough to do that. If you want to use some custom classes for block I offer you add them from admin panel in block manager and build your CSS starting from your custom class.

**Comment by ghost** [comment]
Great, that's the approach I took. thanks for the pointers! :)

Regards,
Nipun Senadheera
