### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by Alexder** [cscart/cscart-boilerplate#42]
Small typo in "templates / views / checkout / components / checkout_login.tpl"
there is unnecessary ">" after {__("create_guest_account")} on line 67
<img width="381" alt="2016-03-02 14 13 36" src="https://cloud.githubusercontent.com/assets/965842/13458903/2bcde320-e081-11e5-98bd-2a720748ad44.png">

**Comment by eermol** [comment]
[this commit](https://github.com/cscart/cscart-boilerplate/commit/6b98c05c361233d4ea30c08f2f26919e63d8e5f5) resolve it.
Thanks a lot for your help.
