### ISSUE TITLE
Button "Reorder this order" doesn't work

### ISSUE THREAD

**Issue by Alexder** [cscart/cscart-boilerplate#43]
If check previous orders in the account, the button "Reorder this order" doesn't work, it does nothing.

**Comment by eermol** [comment]
Hello! Thanks for help!
We've make a little typo in template, so button doesn't had href attribute.
This [commit](https://github.com/cscart/cscart-boilerplate/commit/652d451d82a61009c69b8ad3073f309522367799) will resolve the problem.
