### ISSUE TITLE
Non responsive checkout

### ISSUE THREAD

**Issue by stevedurr** [cscart/cscart-boilerplate#44]
I'm getting a non responsive cart/basket.

Fresh install no modifications and the cart items do not respond.

Thanks

Steve

**Comment by eermol** [comment]
@stevedurr , Thank your for a report Steve!
Cart items not respond because it build on responsive tables of bootstrap that just wrapping in parent block with scroll. 
You can see how it works [here](http://getbootstrap.com/css/#tables-responsive).

P.S. I might not understand you about the problem. So if it not what you mean, please attach screenshot or link in this issue and I try to help you!

**Comment by stevedurr** [comment]
@eermol 

Thanks for the reply. I think I see what you mean, tables do not respond in Bootstrap, not like they do in the standard CS Cart responsive template. Thats my issue then. The boilerplate cart items section does not respond to the device width the same as the responsive template. Its missing the code that takes the `<td>` and turns it in to a `<div>.`

If you look at the standard install you can see the difference. Is there likely to be an update soon for this?

Thanks

**Comment by eermol** [comment]
@stevedurr 
Yes. We will redesign cart soon. 
Well.. I can not closed this issue and notify you when all changes will be done.

**Comment by stevedurr** [comment]
@eermol I have managed to use the relevant css from the responsive theme to sort the cart items in the boilerplate theme. This of course is a temp fix until there is a new release.

I'm using the theme on a production site (probably not advised) but its just so good. :)

**Comment by kugimiya** [comment]
Hello, @stevedurr.
We redesign cart's page table. There are in this PR: #99
So, I think, that wrap table in parent block with scrolling very bad idea. But, I try to make it more responsive. Can you check, can that close this issue? :)

**Comment by stevedurr** [comment]
@kugimiya Absolutely spot on. Nice work.
