### ISSUE TITLE
quantity selector

### ISSUE THREAD

**Issue by demeldoo** [cscart/cscart-boilerplate#45]
hello,

the quantity selector signs are not logicly applied

https://drive.google.com/file/d/0B4wkwfPFu50ZSmJybUxYZTRKODg/view?usp=drivesdk

**Comment by eermol** [comment]
@demeldoo Thank you for a reply! 
fixed by this [commit](https://github.com/cscart/cscart-boilerplate/commit/34584cff307e0d6a712f073cf448430c3a2748d3)
