### ISSUE TITLE
Billing options template messed up

### ISSUE THREAD

**Issue by Cig-group** [cscart/cscart-boilerplate#47]
![cc-problem](https://cloud.githubusercontent.com/assets/18389350/14416688/a25213f6-ffb5-11e5-99a8-7117dc777dac.jpg)

**Comment by eermol** [comment]
@Cig-group , thank you for the reply. 
This issue fixed by this [commit](https://github.com/cscart/cscart-boilerplate/commit/7d3e88d42090e0cc7d146155bf610d91e51e931b)
