### ISSUE TITLE
Manage store logos programmatically

### ISSUE THREAD

**Issue by matthewmorek** [cscart/cscart-boilerplate#48]
Currently, the way to add a custom logo to the store leads only through the Theme Editor, which is not ideal, as this relies on providing theme Styles, and restricts file types to PNG, GIF, and JPG.

There should be an easier way to included a store logo, especially in formats other than the above (i.e.: SVG). For example, for my current theme, I had to change the `logo.tpl` file to look like this:

``` html
{** block-description:tmpl_logo **}
{assign var=theme_url value="{$config.current_location}/design/themes/{$settings.theme_name}"}
<a href="{""|fn_url}" title="{$settings.Company.company_name}" class="logo">
    <img src="{$theme_url}/media/images/logos/logo-default.svg">
</a>
```

**Comment by eermol** [comment]
This is not a problem of Boileplate theme. If you have a suggestion how improve CS-Cart, you should post it in [forum](http://forum.cs-cart.com/) .
