### ISSUE TITLE
submenu unusable with 2 rows menu

### ISSUE THREAD

**Issue by Cig-group** [cscart/cscart-boilerplate#49]
when menu is long and goes 2 rows, submenu from the first row is unreachable
![has-submenu-1](https://cloud.githubusercontent.com/assets/18389350/14575132/86240cb4-0368-11e6-9b21-83e2c116d259.jpg)
![has-submenu-2](https://cloud.githubusercontent.com/assets/18389350/14575142/8d530a30-0368-11e6-89cc-feb19782543e.jpg)

fix: update styles.less

.has-submenu .dropdown-menu {
    left: auto;
top: initial;
}

**Comment by eermol** [comment]
@Cig-group , thank you for the reply! 
Now it works [commit](https://github.com/cscart/cscart-boilerplate/commit/a46242c365e662653c4e15e7e4b89c673f2c1e18)
