### ISSUE TITLE
[!] Design: Products: The Big Picture template: Tabs were not displayed on product details pages. Fixed.

### ISSUE THREAD

**Issue by demeldoo** [cscart/cscart-boilerplate#50]
it seems that this bug is still present in the latest boilerplate

**Comment by eermol** [comment]
@demeldoo , thank you for the report and sorry for long answer. 
This issu fixed by this commit.
https://github.com/cscart/cscart-boilerplate/commit/354e21b44568d498dc59040f31d9553d6143e3d1
