### ISSUE TITLE
template editor 4.3.7

### ISSUE THREAD

**Issue by demeldoo** [cscart/cscart-boilerplate#51]
hello,

the template editor has no functionalities like for other themes

https://drive.google.com/file/d/0B4wkwfPFu50ZdER0MHBfMnYzREU/view?usp=drivesdk

**Comment by dswwood** [comment]
Same problem with 4.3.6. Only 'Logo' can be changed.

**Comment by eermol** [comment]
@demeldoo , @dswwood , this problem has been solved in CS-Cart 4.3.8 after move theme editor in admin panel.
