### ISSUE TITLE
Upgrade to Bootstrap 4

### ISSUE THREAD

**Issue by i198622** [cscart/cscart-boilerplate#56]
Hi guys maybe we will create a branch and will trying to upgrade the theme to a new Bs. ?

**Comment by kugimiya** [comment]
@i198622 Если отталкиваться от этой [статьи](https://designmodo.com/migrate-bootstrap-4), выглядит не сложно. Но кто из тестеров будет согласен весь этот переезд обтестить? :)

**Comment by kugimiya** [comment]
After the discussion, we came to the conclusion that any changes in the topic related to changing Bootstrap would be meaningless to do without integrating the bootstrap as the source code.
But now the kernel does not support SASS for Bootstrap 4, or the new LESS syntax for Bootstrap 3.3.7
In the near future, we will not do this.
