### ISSUE TITLE
Reviews tab is blank on product page

### ISSUE THREAD

**Issue by dswwood** [cscart/cscart-boilerplate#57]
The "Reviews" tab on product pages shows nothing. There are reviews for the products, and I see them viewing the source.

Also, the cursor over the tab is a text cursor rather than a pointer.

**Comment by eermol** [comment]
Thank you for reply.
It fixed in this [commit](https://github.com/cscart/cscart-boilerplate/commit/4fc665afad2457e6c22c5dc6ccedb5ce93600c43)
