### ISSUE TITLE
Only the primary image shows on the product page

### ISSUE THREAD

**Issue by dswwood** [cscart/cscart-boilerplate#58]
When a product has several images, the thumbnails show up fine. But only the first image is shown when you click on its thumbnail.

**Comment by amelekesov** [comment]
I think this commit will help you https://github.com/cscart/cscart-boilerplate/pull/59/commits/1e67537c65941ad4a0ef74e9f7b36d1feb36b99a

**Comment by dswwood** [comment]
That does not work here. It enlarges the height of the container showing all images at the same time. To clarify the problem, this is on the product details page.

**Comment by Cig-group** [comment]
This fix doesnt solve the problem, now all images are shown together, one below another

**Comment by kugimiya** [comment]
Issue was fixed long time ago.
