### ISSUE TITLE
Debuger does not work

### ISSUE THREAD

**Issue by jacekmichalski** [cscart/cscart-boilerplate#6]
The template does not have debuger view included.

Message
Uncaught --> Smarty: Unable to load template tygh 'views/debugger/debugger.tpl' <-- thrown

**Comment by amelekesov** [comment]
CS-Cart Debugger will work as before in one of the next releases. To avoid duplicating the code, the customer area will use the debugger of the admin panel.

If you want to fix the issue quickly, copy the design/themes/responsive/templates/views/debugger directory into the cscart-boilerplate design/themes/theme_name/templates/views/debugger directory.
