### ISSUE TITLE
Grid view formatting

### ISSUE THREAD

**Issue by dswwood** [cscart/cscart-boilerplate#60]
By default, Grid view items are formatted like this:
![gridviewitem](https://cloud.githubusercontent.com/assets/19874339/16007252/61df3eb4-313f-11e6-99f8-bbcb1f7c2525.png)

**Comment by kugimiya** [comment]
Hi, @dswwood, now i cannot reproduce this issue, seems like its was fixed. Can you tell, under what conditions is the issue reproduced?

**Comment by kugimiya** [comment]
So, @dswwood, I find commit with fix: https://github.com/cscart/cscart-boilerplate/commit/50b8065073f17969216dc675daf26cc0916e4b2e#diff-c304272f53947534fb30960fa2dec3a5

Can you reply, is this fix help you and reproduce this issue yet?

**Comment by kugimiya** [comment]
We fix this.
