### ISSUE TITLE
Clone Theme doesn't work

### ISSUE THREAD

**Issue by dswwood** [cscart/cscart-boilerplate#61]
Backend, Design|Themes|Clone Theme does not clone the theme correctly. To verify, clone the theme and diff it with the old one.

**Comment by torunar** [comment]
Hello, @dswwood.

Please, specify the following:
- What version of CS-Cart are you using?
- How did you installed the Boilerplate itself (by cloning it into the `design/themes/boilerplate` **OR** by downloading the archive and installing it via Design > Themes > Add theme)?

**Comment by dswwood** [comment]
CSC v4.3.6
Installed it by downloading the archive and installing via Design > Themes > Add Theme

**Comment by kugimiya** [comment]
Hello, @dswwood. I can not reproduce your issue. Can you try to check on current version of CS-Cart?
