### ISSUE TITLE
Didn't work on clear basic instllation cs-cart 4.3.8_rus

### ISSUE THREAD

**Issue by stasok** [cscart/cscart-boilerplate#64]
On cs-cart 4.3.8 doesnt working.
Don't creating big css file, and directory. http://joxi.ru/1A5Xb4JuKjQnR2
Try dev_css, not help. On 4/3/6 theme work correct. http://joxi.ru/KAxbeOMf45RKZm
Please help me someone.

**Comment by amelekesov** [comment]
I suppose you have wrong directory permissions on your server.
Follow this instruction http://docs.cs-cart.com/4.3.x/install/useful_info/permissions.html#permissions-for-cs-cart

**Comment by stasok** [comment]
Right permissions, when enable resposive theme all work fine.
/var and all directory in 777
delete cache, all generate normal.

**Comment by stasok** [comment]
I have the same error on two different hosting, there theme work correct on 4/3/7 version right now.

**Comment by stasok** [comment]
http://bisontruck.trendkey.ru/
http://438rus.stasok.com/

**Comment by stasok** [comment]
All that i'm do its on Russian Edition of cs-cart.

**Comment by stasok** [comment]
Theme work correct on international 4.3.8  version on cs-cart.
Problem in cs-cart Russian Edition.

**Comment by stasok** [comment]
Problem solved. Somthing wrong in theme, maybe not complete copy all files. When I'm override theme folder, theme start work correct.
