### ISSUE TITLE
Unable to load template after fresh install

### ISSUE THREAD

**Issue by jacekmichalski** [cscart/cscart-boilerplate#66]
After fresh install of cs-cart when I change the theme to boilerplate I get errors:

Unable to load template tygh 'buttons/go.tpl' in 'addons/newsletters/blocks/static_templates/subscribe.tpl'

**Comment by eermol** [comment]
@jacekmichalski , thank you for reply.
Can you say please from where you downloaded Boilerplate?

**Comment by jacekmichalski** [comment]
I just git clone it from here

Another one is here:
Smarty: Unable to load template tygh 'buttons/button.tpl' in 'addons/wishlist/views/wishlist/components/add_to_wishlist.tpl'

![image](https://cloud.githubusercontent.com/assets/16465650/18004449/5b6e8578-6b94-11e6-9e6a-70a98d1172b4.png)

**Comment by jacekmichalski** [comment]
git clone https://github.com/cscart/cscart-boilerplate.git design/themes/mythemename

**Comment by eermol** [comment]
have you try to delete var/cache folder?

**Comment by jacekmichalski** [comment]
Yes, it doesn't help. When I uninstall addons mentioned in the path, theme contiunes to work. With newsletters addon enabled I still get:

![image](https://cloud.githubusercontent.com/assets/16465650/18005410/1ca94da4-6b9a-11e6-894a-2fd4028b77e8.png)

**Comment by Cig-group** [comment]
i confirm, same issue

**Comment by stevedurr** [comment]
This is a buttons issue. If you check the message on the service unavailable screen it tells you the issue. Buttons are no longer stored in a buttons folder, there are in the theme/templates/common folder. There are a few addons that will show this issue. You need to alter the button reference in the add on or use the "my changes" addon to override the file.

**Comment by kugimiya** [comment]
Hi, @jacekmichalski @Cig-group, thanks for the report. Now, i can not to reproduce your issue, it seems work well. Can you tell, in what version of CS-Cart it was happened?

**Comment by somily88** [comment]
i confirm, same issue

**Comment by stevedurr** [comment]
> i confirm, same issue

Hi, See my comment above. The buttons/go.tpl just needs amending/overriding.
