### ISSUE TITLE
Product feature table disappear on cm-tooltip hover

### ISSUE THREAD

**Issue by jacekmichalski** [cscart/cscart-boilerplate#7]
Product feature table disappear on cm-tooltip hover. It's jquery related. What is ETA till js is rewriten and you get rid of e.g. jquery UI?

**Comment by amelekesov** [comment]
Fixed by https://github.com/cscart/cscart-boilerplate/commit/3373d802c6ffa6a5b15af44e4bffa7a9bee5c885
