### ISSUE TITLE
Old Bootstrap 2 class in TPL files

### ISSUE THREAD

**Issue by elnino79** [cscart/cscart-boilerplate#71]
Files listed below have old Boostrap 2 class **"hidden-phone"**:
/templates/common/image.tpl 
/templates/common/pagination.tpl 
/templates/common/select_object.tpl 

Boostrap 2 class **"hidden-tablet"**:
/templates/common/select_object.tpl

Boostrap 2 class **"span1"** and **"span2"**
/templates/index.tpl

**Comment by kugimiya** [comment]
Hello, @elnino79 
Thanks for reply, we fix this in #96 PR. So, PR is merged, thats mean fix include in master-branch too. :)
