### ISSUE TITLE
Google reCAPTCHA 

### ISSUE THREAD

**Issue by elnino79** [cscart/cscart-boilerplate#74]
The new addon Google reCAPTCHA, introduced in CS-Cart 4.4.3 does not work.

**Comment by alpharder** [comment]
CS-Cart 4.5.1, which will be released in a few days, will solve this problem. However, the issue for CS-Cart 4.4.3 will be solved separately.

**Comment by elnino79** [comment]
Google reCAPTCHA working in new version.
