### ISSUE TITLE
Uncaught TypeError: elm.size is not a function

### ISSUE THREAD

**Issue by elnino79** [cscart/cscart-boilerplate#75]
**Error type**: JS 
**File**: /design/themes/cscart-boilerplate-master/js/core.js
**When**: after passing to the next page of product list
**CS-Cart version**: 4.4.3 (tested on clean version)
**Error msg:** "Uncaught TypeError: elm.size is not a function"
**Ajax request**: /category/page-2/?result_ids=pagination_contents&is_ajax=1

**Comment by elnino79** [comment]
I found a solution in responsive theme. In fn scrollToElm(), before (line 1442, core.js):
```
            if (!elm.size()) {
                return;
            }
```
you have to add:
```
            if (typeof(elm) === 'string') {
                if (elm.length && elm.charAt(0) !== '.' && elm.charAt(0) !== '#') {
                    elm = '#' + elm;
                }
                elm = $(elm);
            }  
```
Normally to scrollToElm() is passed jQuery object, but sometime other function just pass class name.

**Comment by alpharder** [comment]
Thanks for the report.

**Comment by moondawg69** [comment]
I replaced that code as per the solution by elino79 but then that results in:

'undefined is not an object (evaluating 'elm.offset().top')'

Which then breaks the product filters, you can only filter 'once' and then not again, without refreshing the page.

Kind of a breaking point of the site in general, I would appreciate a fix asap please, CS Cart team.

**Comment by torunar** [comment]
Hello, @elnino79, @moondawg69.
Can you please check if #83 fixes the issue for you?

**Comment by kugimiya** [comment]
Hi, @elnino79 , @moondawg69.
Can you check, is PR #89 fixes this issue?

**Comment by kugimiya** [comment]
PR #89 fix this issue.
