### ISSUE TITLE
UI items collapsing on error message

### ISSUE THREAD

**Issue by moondawg69** [cscart/cscart-boilerplate#78]
Various samples, see attachments for details. 

Happens in all major browsers, if you generate an error message (do not enter any data etc.) then the fields collapse and looks awful. Needs looking at before being put into a production environment really...

The generated HTML, example: 

<span id="track_order_item1065_error_message" class="help-inline help-block"><p>The <b>Track your order(s)</b> field is mandatory.</p></span>

However, this help block is inside the input group.

**The help block should be outside the input group:** 

https://github.com/twbs/bootstrap/issues/10618

I cannot find that file that controls those errors, where are they?

<img width="687" alt="screen shot 2017-05-09 at 00 18 47" src="https://cloud.githubusercontent.com/assets/1304000/25829416/da3536cc-344d-11e7-835c-3608b6ee3d43.png">
<img width="376" alt="screen shot 2017-05-09 at 00 20 20" src="https://cloud.githubusercontent.com/assets/1304000/25829417/da57596e-344d-11e7-847b-b2c42d4dc87c.png">

**Comment by kugimiya** [comment]
Hello, @moondawg69
Thank you for your report. The fix is included in the pull request #98 .
