### ISSUE TITLE
Top menu dropdown caret is showing when category doesn't have any subcategory.

### ISSUE THREAD

**Issue by enverarslan** [cscart/cscart-boilerplate#81]
If category does not have any subcategory we must hide caret. 

https://github.com/cscart/cscart-boilerplate/blob/master/templates/blocks/topmenu_dropdown.tpl#L26

Exist code: 
`<a {if $item1_url} href="{$item1_url}"{/if} class="dropdown-toggle">{$item1.$name} <span class="caret"></span></a>`

Change to:
`<a {if $item1_url} href="{$item1_url}"{/if} class="dropdown-toggle">{$item1.$name}{if $item1.$childs} <span class="caret"></span>{/if}</a>`

**Comment by kugimiya** [comment]
Hello, @enverarslan  
Thank you for your report. The fix is included in the pull request #93 .
