### ISSUE TITLE
Add to Cart Button not Working

### ISSUE THREAD

**Issue by insynch** [cscart/cscart-boilerplate#82]
Using a fresh install from URL. All seems fine, although when installing an the Webkul Package Builder addon on the Add to Cart button doesnt work on standard products, also not able to remove items from the Cart, this sounds like a Jquery error but nothing is showing in the console. Error also occured when creating a directory in the root folder with some jquery files, seems to be confilcting with boilerplate Jquery

I have tried using a pre installed theme and all works fine

Thanks

**Comment by kugimiya** [comment]
Hello, @insynch. We not support this addon. Try to contact with Webkul for get nformation about this.
